[envs.lint]
skip-install = true
dependencies = [
    "flake8>=4.0.0",
    "pyproject-flake8>=0.0.1a2",
    "mypy>=0.901",
]

[envs.lint.scripts]
# TODO: Change to flake8 when it supports pyproject.toml
style = "pflake8 src"
typing = "mypy --install-types --non-interactive src"
all = ["style", "typing"]

[envs.test]
dependencies = [
	"pytest>=7.1.2",
]

[envs.test.scripts]
doctest = "pytest --doctest-modules src"
all = ["doctest"]

[envs.test-matrix]
template = "test"

[[envs.test-matrix.matrix]]
python = ["37", "38", "39", "310", "311"]

[envs.docs]
skip-install = true
dependencies = [
    "sphinx>=4.4.0",
    "gitchangelog>=3.0.4",
    "mako>=1.2.0",
    "furo>=2022.4.7",
    "sphinx-reredirects>=0.0.1",
    "sphinx-last-updated-by-git>=0.3.2",
    "sphinx-autoapi>=1.8.4",
    "tomli>=2.0.1;python_version<'3.11'",
    "sphinx-better-subsection>=0.1",
]

[envs.docs.scripts]
build = "sphinx-build -b dirhtml docs docs/_build/html"
